--USERS TABLE SETUP
CREATE TABLE USERS (
    USER_ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME varchar(20) NOT NULL,
    LAST_NAME varchar(20) NOT NULL,
    EMAIL text NOT NULL,
    PWD text NOT NULL,
    TERMS BOOLEAN NOT NULL,
    CREATED timestamp NOT NULL
);

--WORKOUTS TABLE SETUP
CREATE TABLE WORKOUTS (
    WORKOUT_ID INT PRIMARY KEY,
    WORKOUT_TYPE VARCHAR(20) NOT NULL,
    WORKOUT_NAME VARCHAR(50) NOT NULL,
    WORKOUT_DESC TEXT NOT NULL,
    DIST FLOAT,
    DIST_KM FLOAT,
    PHASE VARCHAR(20) NOT NULL,
    DIST_LEVEL_MIN FLOAT NOT NULL,
    DIST_LEVEL_MAX FLOAT NOT NULL,
    RACE FLOAT NOT NULL
);

--RUNS TABLE SETUP
CREATE TABLE RUNS (
    RUN_ID INT PRIMARY KEY,
    RUN_TYPE VARCHAR(20) NOT NULL,
    RUN_NAME VARCHAR(50),
    RUN_DESC TEXT
);

--PLANS TABLE SETUP
CREATE TABLE PLANS (
    PLAN_ID BIGSERIAL,
    DATE DATE,
    DAY_CODE INT,
    DAY_DESC VARCHAR(10),
    WEEK INT,
    PHASE VARCHAR(10),
    DIST FLOAT,
    DIST_KM FLOAT,
    RUN_ID INT,
    WORKOUT_ID INT,
    PACE VARCHAR(10),
    PRIMARY KEY (PLAN_ID, DATE)
)
--USER_PLANS TABLE SETUP
CREATE TABLE USER_PLANS (
    USER_ID INT,
    PLAN_ID INT,
    DIST FLOAT,
    START_DATE DATE,
    RACE_DATE DATE,
    RACE_NAME VARCHAR(50),
    PRIMARY KEY (USER_ID, PLAN_ID)
)

--COPYING WORKOUTS.CSV INTO WORKOUTS TABLE FROM PSQL CLI
\copy workouts from 'C:\Users\scottn\Documents\git_repos\MachineCoaching\workouts\workouts.csv' with DELIMITER ',' CSV HEADER;
\copy runs from 'C:\Users\scottn\Documents\git_repos\MachineCoaching\workouts\runs.csv' with DELIMITER ',' CSV HEADER;